baseURL: 'https://philippraven.com/'
languageCode: 'en-us'
title: 'philipp raven'
theme: hugo-profile

Paginate: 12
# disqusShortname: gurusabarish
# googleAnalytics: G-DWJJVE27WD

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:

    - identifier: about
      name: About
      title: About
      url: '#'
      weight: 1

    - identifier: home
      parent: about
      name: Home
      title: Home
      url: '/#'
      weight: 1

    - identifier: about-me
      parent: about
      name: About me
      title: About me
      url: /#about
      weight: 2

    - identifier: experience
      parent: about
      name: Experience
      title: Experience
      url: '/#experience'
      weight: 3

    - identifier: education
      parent: about
      name: Education
      title: Education
      url: '/#education'
      weight: 4

    - identifier: projects
      parent: about
      name: Projects
      title: Projects
      url: '/#projects'
      weight: 5

    - identifier: contact
      parent: about
      name: Contact me
      title: Contact me
      url: '/#contact'
      weight: 6


    - identifier: blog
      name: Blog
      title: Blog posts
      url: /blog
      weight: 7

    - identifier: gallery
      name: Gallery
      title: Gallery
      url: /gallery
      weight: 8

    - identifier: search
      name: Search
      title: Search
      url: /search
      weight: 9

    # - identifier: tags
    #   name: Tags
    #   title: Tags
    #   url: /tags
    #   weight: 2

    # - identifier: songs
    #   name: Songs
    #   title: Songs
    #   url: /songs
    #   weight: 3

params:
  title: 'philipp raven'
  description: 'ai engineer - artist - creator'
  # staticPath: ''
  favicon: '/icon.png'
  thumbnailWidth: 350
  thumbnailHeight: 250
  truncateLength: 250

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  theme:
    disableThemeToggle: false
    # defaultTheme: "light" # dark

  # font:
  #   fontSize: 1.5rem # default: 1rem
  #   fontWeight: 500 # default: 400
  #   lineHeight: 1 # default: 1.5
  #   textAlign: right # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    disableSearch: true
  #   align: mx-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
  #   brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
  #   brandName: "Profile" # Brand name for the brand | default is the title variable

  #   menus:
  #     disableAbout: true
  #     disableExperience: true
  #     disableEducation: true
  #     disableProjects: true
  #     disableAchievements: true
  #     disableContact: true

  # Hero
  hero:
    enable: true
    intro: "Hi, I'm"
    title: 'Philipp'
    # subtitle: "Unger"
    content: 'ai engineer - artist - creator'
    image: /images/profile-pic-3.webp
    # button:
    # enable: true
    # name: "Resume"
    # url: "#"
    # download: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/GrafKnusprig
        - icon: fab fa-instagram
          url: https://www.instagram.com/philippraven/
        - icon: fab fa-soundcloud
          url: https://soundcloud.com/mufuki
        - icon: fab fa-youtube
          url: https://www.youtube.com/channel/UCJ29i8qd-09tz47yZP7lxrA
        - icon: fas fa-cube
          url: https://www.thingiverse.com/search?q=grafknusprig
        # - icon: fab fa-twitter
        # url: https://example.com
      # customIcons:
      # - icon: /fav.png
      # url: "https://example.com"

  # About
  about:
    enable: true
    title: 'About Me'
    skillstitle: 'Stuff I use regularly'
    # image: "/images/profile-pic-1.webp"
    content: |-
      When you ask someone to tell you about themselves, it's never easy.

      I've been interested in all sorts of things all my life and my interests are constantly changing. I live to evolve and discover new joys in life.
      If I had to describe myself in one word, it would be that I am an artist.

      After school, I studied computer science and now have over 10 years of professional experience as a full stack software engineer.

      Since one skill alone does not satisfy me, I have many hobbies.
      I enjoy personalizing everything in my life, adapting things and processes to my needs.
      Here I can live out my creativity to the full.

      My passions also include art and music. I often do small favors for my friends. Whether it's 3D models, logos, programs, websites, videos or photoshoots... the list is truly endless.

      Whenever possible, I make my designs and programs open source. I'm a big advocate of that.

      <br>

      On this website I want to give an overview of my projects. Unfortunately, I can't keep up with posting everything I do here. But I'll try to post something from time to time. 

      ---


      <b>FAQ:</b>
      Why the nickname raven? - Well, I like ravens. ;)
      </p>
      <br><br><br><br><br>

    skills:
      enable: true
      title: ''
      items:
        - '[AdobeSuite](https://www.adobe.com/creativecloud.html)'
        - '[Arduino](https://www.arduino.cc/)'
        - '[Audacity](https://www.audacityteam.org/)'
        - '[Blender](https://www.blender.org/)'
        - '[C#](https://docs.microsoft.com/en-us/dotnet/csharp/)'
        - '[ChatGPT](https://chat.openai.com/)'
        - '[FFmpeg](https://ffmpeg.org/)'
        - '[FreeCAD](https://www.freecad.org/)'
        - '[GitHub](https://github.com/)'
        - '[GitLab](https://about.gitlab.com/)'
        - '[HUGO](https://gohugo.io/)'
        - '[Java](https://www.java.com/)'
        - '[JavaScript](https://www.w3schools.com/js/)'
        - '[JetBrains](https://www.jetbrains.com/)'
        - '[MiKTeX](https://miktex.org/)'
        - '[MPC Beats](https://www.akaipro.com/mpc-beats)'
        - '[Node.js](https://nodejs.org/en/)'
        - '[OpenSCAD](https://openscad.org/)'
        - '[OBS-Studio](https://obsproject.com/)'
        - '[PyTorch](https://pytorch.org/)'
        - '[Python](https://www.python.org/)'
        - '[Raspberry Pi](https://www.raspberrypi.org/)'
        - '[Scratch](https://scratch.mit.edu/)'
        - '[Shotcut](https://shotcut.org/)'
        - '[UltiMaker Cura](https://ultimaker.com/software/ultimaker-cura)'
        - '[VisualStudio](https://visualstudio.microsoft.com)'
        - '[VoiceMeeter](https://vb-audio.com/Voicemeeter/)'

  # Experience
  experience:
    enable: true
    title: 'Experience'
    items:
      - job: 'Data Scientist'
        company: 'University of Passau - Chair of Software Engineering II '
        companyUrl: 'https://www.fim.uni-passau.de/en/chair-for-software-engineering-ii/'
        date: 2024 - current
        featuredLink:
          enable: true
          name: 'InnRaum³'
          url: 'https://www.innraum.eu/'
        # info:
        #   enable: true
        #   content: I am currently working at the InnRaum³ as part of the INTERREG project. There I am responsible for running various courses for school pupils, students, trainees and employees. My work includes design from 3D model to print, AI development, setting up the makerspace and recruiting new members, safety training and machine maintenance.
        content: |-
          I work as a research assistant at the Chair of Software Engineering 2 under Prof. Gordon Fraser.

          I am currently working at the InnRaum³ as part of the INTERREG project. There I am responsible for running various courses for school pupils, students, trainees and employees. My work includes design from 3D model to print, AI development, setting up the makerspace and recruiting new members, safety training and machine maintenance.

      - job: 'Robotics Trainer (honorary)'
        company: Maristengymnasium Fürstenzell
        companyUrl: 'https://mgf.de/'
        date: 2023 - current
        content: I honorarily work as a trainer for the robotics course at the Maristengymnasium Füstenzell. Here, I teach children in grades 5-11 how to program autonomous robots using Scratch and Python.
      - job: 'Software Developer'
        company: 'DAP Systems'
        companyUrl: 'https://dap-systems.de/'
        date: '2014 - 2023'
        # featuredlink:
        # enable: true
        # name: "view the project"
        # url: "https://example.com"
        content: |-
          I worked as a software developer at [DAP Systems.](https://dap-systems.de/) in Passau, BY Germany.
          - Fullstack developer for WebReporting, ImageSurfer, RadioXpert-Web [2019 - 2023]
          - Backend developer for RadioXpert, Evogenius Reporting, TVScope [2014 - 2019]

          I have experience in ASP.NET, Angular, C#, CSS, EXT JS, HTML, JavaScript, Less, .Net Framework / Core, Node.js, PHP, SQL, TypeScript and more.

      - job: 'Media Computer Scientist'
        company: 'University of Passau - InteLeC-Zentrum'
        companyUrl: 'https://www.uni-passau.de/en/'
        date: '2013 - 2014'
        # featuredLink:
        # enable: true
        # name: "Univideo Website"
        # url: "https://univideo.uni-passau.de/"
        # info:
        # enable: true
        # content: I worked as a software developer for the univideo website and more.
        content: I worked as a web developer for the [univideo website](https://univideo.uni-passau.de/) and more. Doing mainly HTML, CSS and JS.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    # index: true
    items:
      - title: 'Master AI Engineering (M.Sc.)'
        school:
          name: 'University of Passau'
          url: 'https://www.uni-passau.de/en/'
        date: '2023 - current'
        content: My focus is on the development and optimization of deep learning models. My main seminar is “Software Engineering for Kids”, where I am working on automatic hint generation using LLMs for tutorial systems in Scratch.
      - title: 'Bachelor of Computer Science (B.Sc.)'
        school:
          name: 'University of Passau'
          url: 'https://www.uni-passau.de/en/'
        date: '2009 - 2013'
        # GPA: "3.9 out of 5.0"
        content: |-
          Minor:  **Business Administration**

          Bachelor thesis:
            - [**Automatisierung der Kartographierung von Straßenschildern (Automated street sign mapping)**](https://www.forwiss.uni-passau.de/extern/doc/BA_Unger.pdf)
              
              [FORWISS](https://www.forwiss.uni-passau.de/en/), University of Passau, [Chair of Mathematics with focus on Digital Image Processing](https://www.fim.uni-passau.de/en/digital-image-processing/)
        # featuredLink:
        # enable: true
        # name: "My academic record"
        # url: "https://example.com"
      - title: 'High School'
        school:
          name: 'Maristengymnasium Fürstenzell'
          url: 'http://www.mgfuerstenzell.de/'
        content: |-
          - Advanced courses:
            - physics
            - art
          - Senior project: Digital and craft implementation of a 3D optical illusion

  # Achievements
  # achievements:
  # enable: true
  # # title: "Custom Name"
  # items:
  # - title: Google kickstart runner
  # content: I solved all problems with optimal solution.
  # url: https://example.com
  # - title: Facebook Hackathon Winner
  # content: Developed a product using Artificial Intelligence.
  # - title: Hugo Profile
  # content: Developed a theme and getting 1K+ downloads per month.
  # url: "https://github.com/gurusabarish/hugo-profile"
  # - title: Microsoft Imagine Runner
  # content: We are developed a product which can help others.
  # - title: Google Summer of Code
  # content: Contributed to a open source project.
  # url: https://example.com

  # projects
  projects:
    enable: true
    # title: "custom name"
    items:
      - title: 'Hunt: Showdown - Loadout Randomizer'
        content: 'Hunt: Showdown - Loadout Randomizer is a local browser application that generates random loadouts for the game Hunt: Showdown. It is perfectly suited to be used as a browser plugin in OBS-Studio and similar applications and was made exactly for this purpose.'
        image: /images/projects/hunt-randomizer-1.webp
        featured:
          name: Start Randomizer
          link: https://grafknusprig.github.io/HuntShowdownLoadoutRandomizer/Randomizer.html
        badges:
          - 'html'
          - 'javascript'
        links:
          - icon: fab fa-github
            url: https://github.com/GrafKnusprig/HuntShowdownLoadoutRandomizer
      - title: 'BirdCLEF 2024'
        content: 'Bird species identification from audio, focused on under-studied species in the Western Ghats, a major biodiversity hotspot in India.'
        image: /images/projects/birdclef-2024.webp
        featured:
          name: Read Blog Post
          link: /blog/projects/birdclef-2024
        badges:
          - "kaggle"
          - "competition"
          - "machine learning"
          - "pytorch"
        links:
          - icon: fab fa-kaggle
            url: https://www.kaggle.com/competitions/birdclef-2024

  #Contact
  contact:
    enable: true
    title: 'Contact me'
    content: If you want to contact me, you can always send me an email.
    email: philipp.info@proton.me
    btnName: Mail me

  footer:
    recentPosts: true
    # socialNetworks:
    # github: https://github.com
    # linkedin: https://linkedin.com
    # twitter: https://twitter.com
    # instagram: https://instagram.com
    # facebook: https://facebook.com

outputs:
  home:
    - HTML
    - JSON
